#!/usr/bin/env python3
"""Generate a Python connector stub module from the AsyncAPI spec.

Parses specs/pds-connector-base.yaml (the transport contract) and emits
qb_stub.py containing every machine-readable transport fact: channel
addresses, exchange/queue AMQP bindings, content type, and per-operation
delivery modes. The contract test (test_contract.py) imports the generated
module, so any structural change to the spec flows straight into the test —
and generation FAILS if the spec loses a structure the protocol relies on.

Usage: python3 tools/asyncapi-stub/generate_stub.py  (from the repo root or this dir)
"""

import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
SPEC = HERE.parents[1] / "specs" / "pds-connector-base.yaml"
OUT = HERE / "qb_stub.py"


def fail(msg: str) -> None:
    sys.exit(f"generate_stub: SPEC CONTRACT BROKEN — {msg} ({SPEC})")


def main() -> None:
    spec = yaml.safe_load(SPEC.read_text())

    if spec.get("asyncapi", "").split(".")[0] != "3":
        fail("expected an AsyncAPI 3.x document")

    content_type = spec.get("defaultContentType")
    if not content_type:
        fail("defaultContentType missing")

    channels = spec.get("channels") or {}
    ops = spec.get("operations") or {}

    # --- broadcast exchange -------------------------------------------------
    broadcast = None
    for name, ch in channels.items():
        amqp = (ch.get("bindings") or {}).get("amqp") or {}
        if amqp.get("is") == "routingKey" and "exchange" in amqp:
            broadcast = {
                "channel": name,
                "address": ch.get("address"),
                "name": amqp["exchange"].get("name"),
                "type": amqp["exchange"].get("type"),
                "durable": amqp["exchange"].get("durable", False),
            }
    if broadcast is None:
        fail("no exchange-bound channel (broadcast) found")
    if broadcast["type"] != "fanout":
        fail(f"broadcast exchange type is {broadcast['type']!r}, expected 'fanout'")

    # --- queue channels -----------------------------------------------------
    def queue_channel(prefix: str) -> dict:
        for name, ch in channels.items():
            address = ch.get("address") or ""
            amqp = (ch.get("bindings") or {}).get("amqp") or {}
            if address.startswith(prefix) and amqp.get("is") == "queue":
                q = amqp.get("queue") or {}
                return {
                    "channel": name,
                    "address": address,
                    "durable": q.get("durable", False),
                    "exclusive": q.get("exclusive", False),
                    "auto_delete": q.get("autoDelete", False),
                }
        fail(f"no queue channel with address prefix {prefix!r}")

    request_q = queue_channel("req.")
    responses_q = queue_channel("responses.")
    dlq = queue_channel("pds.dlq")

    # --- operations & delivery modes ----------------------------------------
    def delivery_mode(op_name: str) -> int:
        op = ops.get(op_name)
        if op is None:
            fail(f"operation {op_name!r} missing")
        return ((op.get("bindings") or {}).get("amqp") or {}).get("deliveryMode", 1)

    for required in ("publishRequest", "consumeRequest", "publishConnectorResponse",
                     "publishAggregatedResponse"):
        if required not in ops:
            fail(f"operation {required!r} missing")

    lines = [
        '"""GENERATED by generate_stub.py from specs/pds-connector-base.yaml — do not edit."""',
        "",
        f"SPEC_TITLE = {spec['info']['title']!r}",
        f"SPEC_VERSION = {spec['info']['version']!r}",
        f"CONTENT_TYPE = {content_type!r}",
        "",
        f"BROADCAST_EXCHANGE = {broadcast['name']!r}",
        f"BROADCAST_EXCHANGE_TYPE = {broadcast['type']!r}",
        f"BROADCAST_EXCHANGE_DURABLE = {broadcast['durable']!r}",
        "",
        f"REQUEST_QUEUE_TEMPLATE = {request_q['address']!r}",
        f"REQUEST_QUEUE_DURABLE = {request_q['durable']!r}",
        f"RESPONSE_QUEUE_TEMPLATE = {responses_q['address']!r}",
        f"RESPONSE_QUEUE_DURABLE = {responses_q['durable']!r}",
        f"DEAD_LETTER_QUEUE = {dlq['address']!r}",
        "",
        f"DELIVERY_MODE_REQUEST = {delivery_mode('publishRequest')}",
        f"DELIVERY_MODE_CONNECTOR_RESPONSE = {delivery_mode('publishConnectorResponse')}",
        f"DELIVERY_MODE_AGGREGATED_RESPONSE = {delivery_mode('publishAggregatedResponse')}",
        "",
        "",
        "def request_queue(pds_id: str) -> str:",
        '    return REQUEST_QUEUE_TEMPLATE.replace("{pdsId}", pds_id)',
        "",
        "",
        "def response_queue(system_id: str) -> str:",
        '    return RESPONSE_QUEUE_TEMPLATE.replace("{systemId}", system_id)',
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"generated {OUT.relative_to(HERE.parents[1])} from spec v{spec['info']['version']}")


if __name__ == "__main__":
    main()
