"""GENERATED by generate_stub.py from specs/pds-connector-base.yaml — do not edit."""

SPEC_TITLE = 'Query Broker — PDS Connector Base'
SPEC_VERSION = '1.0.0'
CONTENT_TYPE = 'application/fhir+json'

BROADCAST_EXCHANGE = 'pds.broadcast'
BROADCAST_EXCHANGE_TYPE = 'fanout'
BROADCAST_EXCHANGE_DURABLE = True

REQUEST_QUEUE_TEMPLATE = 'req.{pdsId}'
REQUEST_QUEUE_DURABLE = True
RESPONSE_QUEUE_TEMPLATE = 'responses.{systemId}'
RESPONSE_QUEUE_DURABLE = True
DEAD_LETTER_QUEUE = 'pds.dlq'

DELIVERY_MODE_REQUEST = 2
DELIVERY_MODE_CONNECTOR_RESPONSE = 2
DELIVERY_MODE_AGGREGATED_RESPONSE = 2


def request_queue(pds_id: str) -> str:
    return REQUEST_QUEUE_TEMPLATE.replace("{pdsId}", pds_id)


def response_queue(system_id: str) -> str:
    return RESPONSE_QUEUE_TEMPLATE.replace("{systemId}", system_id)
